name: version, tag and github release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: salesforcecli/github-workflows/.github/workflows/create-github-release.yml@main
    secrets:
      SVC_CLI_BOT_GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

  # most repos won't use this
  # depends on previous job to avoid git collisions, not for any functionality reason
  # docs:
  #   uses: salesforcecli/github-workflows/.github/workflows/publishTypedoc.yml@main
  #   secrets: inherit
  #   needs: release
