name: version, tag and github release

on:
  push:
    branches: [main]

jobs:
  token:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
  release:
    needs: token
    uses: salesforcecli/github-workflows/.github/workflows/create-github-release.yml@main
    secrets:
      SVC_CLI_BOT_GITHUB_TOKEN: ${{ needs.token.outputs.token }}

  # most repos won't use this
  # depends on previous job to avoid git collisions, not for any functionality reason
  # docs:
  #   uses: salesforcecli/github-workflows/.github/workflows/publishTypedoc.yml@main
  #   secrets: inherit
  #   needs: release
