name: NPM publish

on:
  release:
    # the result of the githubRelease workflow
    types: [ published ]

jobs:
  npm-publish:
    uses: salesforcecli/github-workflows/.github/workflows/npmPublish.yml@main
    with:
      tag: latest
      githubTag: ${{ github.event.release.tag_name }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
